import Config

config :react_demo, ReactDemoWeb.Endpoint,
  http: [ip: {0, 0, 0, 0}, port: 4666],
  debug_errors: true,
  secret_key_base: "kmpnmk2HbLCXfguCqhwY4cT0ed5d7cBirQWJXq/MX8/68Y0VakTLJKjNH4dM2IEU",
  check_origin: false

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :react_demo, ReactDemoWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

config :phoenix_react_server, Phoenix.React.Runtime.Bun,
  cmd: System.find_executable("bun"),
  server_js: Path.expand("../priv/react/server.js", __DIR__),
  port: 5124,
  env: :dev

# Do not print debug messages in production
config :logger, :console, format: "[$level] $message\n"
