import Config

config :react_demo, ReactDemoWeb.Endpoint,
  http: [ip: {0, 0, 0, 0}, port: 4666],
  debug_errors: true,
  secret_key_base: "kmpnmk2HbLCXfguCqhwY4cT0ed5d7cBirQWJXq/MX8/68Y0VakTLJKjNH4dM2IEU",
  check_origin: false

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :react_demo, ReactDemoWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configure Phoenix.ReactServer server for production
# Use environment variable REACT_RUNTIME to switch between :bun and :deno
runtime =
  case System.get_env("REACT_RUNTIME", "bun") do
    "bun" -> Phoenix.ReactServer.Runtime.Bun
    "deno" -> Phoenix.ReactServer.Runtime.Deno
    _ -> Phoenix.ReactServer.Runtime.Bun
  end

config :phoenix_react_ng, Phoenix.ReactServer, runtime: runtime

# Bun configuration for production
config :phoenix_react_ng, Phoenix.ReactServer.Runtime.Bun,
  cmd: System.find_executable("bun"),
  server_js: Path.expand("../priv/react/bun/server.js", __DIR__),
  port: 5124,
  env: :prod

# Deno configuration for production
config :phoenix_react_ng, Phoenix.ReactServer.Runtime.Deno,
  cmd: System.find_executable("deno"),
  server_js: Path.expand("../priv/react/server.js", __DIR__),
  port: 5125,
  env: :prod

# Do not print debug messages in production
config :logger, :console, format: "[$level] $message\n"
